package Model;
// Generated 04/09/2013 00:26:25 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name = "bancos", catalog = "redemais_db")
public class Bancos implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_banco", unique = true, nullable = false)
    private Integer idBanco;
    @Column(name = "codigo", nullable = false, length = 10)
    private String codigo;
    @Column(name = "descricao", nullable = false, length = 10)
    private String descricao;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "bancos")
    private List<Cliente> clientes = new ArrayList<Cliente>();

    public Bancos() {
    }

    public Bancos(String codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public Integer getIdBanco() {
        return this.idBanco;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Cliente> getClientes() {
        return this.clientes;
    }

    public void setClientes(List<Cliente> clientes) {
        this.clientes = clientes;
    }
}
