package Model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Cancelamento generated by hbm2java
 */
@Entity
@Table(name = "cancelamento", catalog = "redemais_db")
public class Cancelamento implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_cancelamento", unique = true, nullable = false)
    private Integer idCancelamento;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_venda", nullable = false)
    private Venda venda;
    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 8)
    private Date hora;
    @Temporal(TemporalType.DATE)
    @Column(name = "data_cancelamento", nullable = false, length = 10)
    private Date dataCancelamento;
    @Column(name = "motivo", nullable = false, length = 450)
    private String motivo;
    @Column(name = "id_user", nullable = false)
    private int idUser;
    @Transient
    private String senha;

    public Cancelamento() {
    }

    public Cancelamento(Venda venda, Date hora, Date dataCancelamento, String motivo, int idUser, String senha) {
        this.venda = venda;
        this.hora = hora;
        this.dataCancelamento = dataCancelamento;
        this.motivo = motivo;
        this.idUser = idUser;
        this.senha = senha;
    }

    public Integer getIdCancelamento() {
        return this.idCancelamento;
    }

    public Venda getVenda() {
        return this.venda;
    }

    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    public Date getDataCancelamento() {
        return this.dataCancelamento;
    }

    public void setDataCancelamento(Date dataCancelamento) {
        this.dataCancelamento = dataCancelamento;
    }

    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public int getIdUser() {
        return idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
}
